export const GET_ALL_TODO_URL = 'http://localhost:8000/todos/all'
export const GET_ACTIVE_TODO_URL = 'http://localhost:8000/todos/active'
export const GET_REMOVED_TODO_URL = 'http://localhost:8000/todos/removed'
export const ADD_TODO_URL = 'http://localhost:8000/todos/add'
export const UPDATE_TODO_URL = 'http://localhost:8000/todos/update'
